### ISSUE TITLE
[bug] the bot doesn't have enough bojo memes

### ISSUE THREAD

**Issue by snarkyerica** [dngfx/MagicBot#1]
maybe add a $bojo command

**Comment by dngfx** [comment]
![CcuWDCF (1)](https://user-images.githubusercontent.com/294904/87245353-9c71b180-c43c-11ea-8150-4065e43aff60.jpg)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245400-d80c7b80-c43c-11ea-95cf-6b9d3b05bdc4.png)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245409-e9ee1e80-c43c-11ea-89e8-abc686512960.png)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245416-02f6cf80-c43d-11ea-9f04-338f331dade2.png)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245429-0be7a100-c43d-11ea-9dfe-4237451de10b.png)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245433-186bf980-c43d-11ea-97f2-f2e395a58720.png)

**Comment by dngfx** [comment]
![image](https://user-images.githubusercontent.com/294904/87245438-202b9e00-c43d-11ea-829c-993faf976b4c.png)

**Comment by femaphore** [comment]
much appreciated
